### PR TITLE
apple icons

### PR DESCRIPTION
**Pull request by mwernimont**
So the icons I have that I made previously have the rounded corners already...so not sure if I was the one who made the icons. I can always make the unrounded corners if you prefer

### CODE REVIEW

**Comment by lawinslow** [comment]
@mwernimont THANKS!

**Comment by mhines-usgs** [comment]
I thought unrounded was the new flat iOS7 way to go?

**Comment by lawinslow** [comment]
v2.1

**Comment by mhines-usgs** [comment]
(keep in mind I know nothing)

**Pull request merged**
